config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i[create show], shallow: true do
    resources :blogs do
      resources :comments, except: %i[show]
    end
  end

  resources :categories
  resources :likes, only: %i[create destroy]

  get '/about', to: 'pages#about', as: 'about_page'
  get '/contact', to: 'pages#contact', as: 'contact_page'
  get '/faqs', to: 'pages#faqs', as: 'faqs_page'

  post '/subscribe', to: 'users#subscribe', as: 'subscribe'

  post '/feedback', to: 'comments#guest_user_feedback', as: 'guest_user_feedback'

  match '*path', via: :all, to: redirect('/404'), constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/views/pages/about_page/_contact_part.html.erb
<div class="bg-white shadow-sm p-5 rounded mt-5">
  <h3 class="text-center text-primary">Let's Talk</h3>
  <div class="m-auto width-55vw">
    <p class="text-muted fs-6 text-font-family">Please take a few moments to share your thoughts, suggestions, or any issues you've encountered while using the website. We appreciate 
      your time and look forward to hearing from you. Thank you for being a part of our learning community!</p>
  </div>
  <%= render 'guest_user_feedback_form' %>
</div>

app/views/pages/about_page/_guest_user_feedback_form.html.erb
<%= form_with url: guest_user_feedback_path, method: :post, id: 'guest-user-feedback' do |form| %>
  <div class="field">
    <%= form.label 'Your Name', class: 'form-label text-muted fw-semibold fs-14px' %><span class="text-danger"> *</span><br />
    <%= form.text_field :name, placeholder: 'Your Full Name', class: 'form-control mb-3', required: true %>
  </div>
  <div class="field">
    <%= form.label :your_email, class: 'form-label text-muted fw-semibold fs-14px' %><span class="text-danger"> *</span><br />
    <%= form.email_field :email, placeholder: 'education.courier@gmail.com', class: 'form-control mb-3', required: true %>
  </div>
  <div class="field">
    <%= form.label :your_message, class: 'form-label text-muted fw-semibold fs-14px' %><span class="text-danger">*</span><br />
    <%= form.text_area(:feedback, rows: '3', class: "form-control mb-3", required: true, placeholder: "Your feedback") %>
  </div>
  <div class="field">
    <%= form.submit 'Send Your Message', class: "btn btn-primary w-100" %>
  </div>
<% end %>

app/views/pages/about_page/_intro_part.html.erb
<div class="row">
  <div class="col-md">
    <%= image_tag('about_us1.jpg', class: 'into-img') %>
  </div>
  <div class="col-md p-5 m-auto text-center">
    <h3 class="text-brand-green heading-font-family">Welcome to EducationCourier.online</h3>
    <p class="text-muted fs-6 text-font-family">At Education Courier, we believe that learning is a lifelong journey that should be accessible 
        to all. We have created this platform to empower individuals like you to share their knowledge, 
        insights, and experiences with the world.
    </p>
    <div class="d-flex justify-content-end">
      <div class="d-flex flex-column align-self-center me-3">
        <h4><%= @admin.name %></h4>
        <p class="text-muted" ><%= @admin.user_summary.title %></p>
      </div>
      <%= image_tag(@admin.user_avatar, class: "rounded-circle width-10rem") %>
    </div>
  </div>
</div>

app/views/pages/about_page/_join_part.html.erb
<div class="text-center p-5 pb-2 shadow-sm story-background">
  <h3 class="heading-font-family">Join Us</h3>
  <div class="m-auto width-55vw">
    <p class="text-muted fs-6 text-font-family">Join the Education Courier community, a place for learners of all levels to explore, 
      engage, and contribute, making education a dynamic and transformative experience for everyone.
    </p>
  </div>
  <div class="d-flex justify-content-center flex-lg-row flex-column">
    <%= add_start_writing_btn('btn btn-light text-gold mb-3') %>
    <%= link_to 'Explore Amazing Content', categories_path, class: 'btn btn-light text-primary mb-3' %>
    <%= button_to 'Subscribe to monthly newsletter', subscribe_path(email: current_user&.email), class: 'btn btn-light text-danger mb-3' %>
  </div>
</div>

app/views/pages/about_page/_offers_part.html.erb
<div class="text-center">
  <h3>What We Offer</h3>
  <p class="fs-6 text-font-family">Education Courier offers a seamless and user-friendly experience for both writers and readers.</p>
  <div class="row">
    <div class="col-md-6 mb-5">
      <div class="card border-0 shadow-sm">
        <div class="row g-0">
          <div class="col-md-5">
            <%= image_tag('about_us3.jpg', class: 'img-fluid rounded-start height-webkit-fill')%>
          </div>
          <div class="col-md-7">
            <div class="card-body">
              <h5 class="card-title heading-font-family">For Writers</h5>
              <p class="card-text text-muted fs-6 text-font-family">You can create and publish your own blog posts, sharing your expertise
                and insights with the world. Whether you've just started your journey or are an 
                experienced professional, your contributions are valuable and can inspire others to learn
                and grow.</p>
              <p class="card-text"><small class="text-muted"><%= add_start_writing_btn('btn text-primary btn-light') %></small></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 mb-5">
      <div class="card border-0 shadow-sm">
        <div class="row g-0">
          <div class="col-md-5">
            <%= image_tag('about_us2.jpg', class: 'img-fluid rounded-start height-webkit-fill')%>
          </div>
          <div class="col-md-7">
            <div class="card-body">
              <h5 class="card-title heading-font-family">For Readers</h5>
              <p class="card-text text-muted fs-6 text-font-family">You have access to a vast repository of knowledge, covering a wide 
                range of tech skills, at your fingertips. You can explore, bookmark, and revisit 
                articles whenever you need a refresher or want to dive deeper into a particular topic.</p>
              <p class="card-text">
                <%= link_to "Join Education Courier", new_user_registration_path, class: 'text-gold text-decoration-none btn btn-light'%>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/about_page/_purpose_part.html.erb
<div class="my-5 p-5 text-center story-background  shadow-sm">
  <h3>Our Purpose</h3>
  <p class="fs-6 text-font-family">Education Courier is dedicated to providing a platform where learners of all levels can contribute, 
      collaborate, and benefit from shared knowledge. We believe in the transformative power of education 
      and the positive impact it can have on individuals and society as a whole. By connecting learners 
      and fostering a vibrant community, we strive to make learning accessible, practical, and engaging.
  </p>
</div>

app/views/pages/about_page/_story_part.html.erb
<div class="my-5 p-5 text-center bg-white shadow-sm" >
  <h3>Our Story</h3>
  <p class="fs-6 text-font-family"> Education Courier was born out of a simple idea - to make learning easier and more enjoyable.
      As avid learners ourselves, we understand the challenges of acquiring new skills and retaining 
      knowledge. We recognized the power of writing down what we learned, as it helps solidify concepts 
      and allows us to revisit them whenever needed. This led us to create a space where learners can 
      write blogs about their newly acquired tech skills and revisit them whenever they desire.
  <p>
</div>

app/views/pages/about_page/_team.html.erb
<div class="shadow-sm text-center p-2rem mb-5 bg-white">
  <%= image_tag(user.user_avatar, class: 'size-12rem rounded-circle mb-4 shadow-sm') %>
  <div>
    <div class="m-auto width-12rem"><h5><%= user.name %></h5></div>
    <p class="text-muted"><%= user.user_summary&.title %></p>
    <div>
      <%= link_to '<i class="bi bi-twitter fs-4"></i>'.html_safe, user.user_summary.twitter,
          class: 'btn text-info', target: :_blank if user.user_summary&.twitter.present? %>
      <%= link_to '<i class="bi bi-github fs-4"></i>'.html_safe, user.user_summary.github, 
          class: 'btn', target: :_blank if user.user_summary&.github.present? %>
      <%= link_to '<i class="bi bi-linkedin fs-4"></i>'.html_safe, user.user_summary.linked_in,
          class: 'btn text-primary', target: :_blank if user.user_summary&.linked_in.present?%>
    </div>
  </div>
</div>

app/views/pages/about_page/_team_part.html.erb
<div class="text-center px-5 pb-5">
  <h3 class="heading-font-family">Our Amazing Team</h3>
  <p class="text-muted fs-6 text-font-family">Education Courier is more than just a platform; it's a community of like-minded learners who are 
    passionate about education and personal growth. Our community thrives on collaboration, feedback, 
    and support. We encourage you to engage with fellow learners, share your thoughts, ask questions, 
    and inspire others. Together, we can create an environment where everyone feels motivated, encouraged, 
    and empowered to pursue their learning goals.</p>
</div>
<div class="d-flex justify-content-around flex-wrap">
  <%= render partial: 'pages/about_page/team', collection: @team, as: :user %>
</div>