config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i[create show], shallow: true do
    resources :blogs do
      resources :comments, except: %i[show]
    end
  end

  resources :categories
  resources :likes, only: %i[create destroy]

  get '/about', to: 'pages#about', as: 'about_page'
  get '/contact', to: 'pages#contact', as: 'contact_page'
  get '/faqs', to: 'pages#faqs', as: 'faqs_page'

  post '/subscribe', to: 'users#subscribe', as: 'subscribe'

  post '/feedback', to: 'comments#guest_user_feedback', as: 'guest_user_feedback'

  match '*path', via: :all, to: redirect('/404'), constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: %i[slugged history]
  validates :title, :content, :summary, :tags, :status, :read_time, presence: true
  validates :read_time, comparison: { greater_than_or_equal_to: 0.5 }

  STATUSES = {
    general: 0,
    featured: 1,
    archived: 2
  }.freeze

  enum status: STATUSES

  belongs_to :user
  belongs_to :category
  has_one_attached :avatar
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  scope :in_descending_order, -> { order(created_at: :desc) }
  scope :in_ascending_order, -> { order(created_at: :asc) }
  scope :published, -> { where('published_at <= ?', DateTime.now) }
  scope :scheduled, -> { where('published_at > ?', DateTime.now) }
  scope :created_today, -> { where('Date(created_at) = ?', Time.zone.today) }
  scope :draft, -> { where(published_at: nil) }

  def should_generate_new_friendly_id?
    title_changed?
  end

  def published?
    published_at.present? && published_at <= DateTime.now
  end

  def draft?
    published_at.blank?
  end

  def scheduled?
    published_at.present? && published_at > DateTime.now
  end

  def parent_comments
    comments.where(parent_id: nil)
  end

  def blog_avatar
    avatar.attached? && avatar || 'blog_default_avatar.jpg'
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include BlogsConcern
  load_and_authorize_resource
  skip_before_action :authenticate_user!, only: %i[show]
  before_action :set_blog, only: %i[show edit destroy update]

  def index
    @blogs = current_user.blogs.all.in_descending_order
    if params[:query] == 'scheduled_blogs'
      @blogs = @blogs.scheduled
    elsif params[:query] == 'draft_blogs'
      @blogs = @blogs.draft
    end
  end

  def show; end

  def new
    @blog = Blog.new
    @categories = Category.all.pluck(:name, :id)
  end

  def create
    @blog = current_user.blogs.new(blog_params)
    if @blog.save
      redirect_to user_blogs_path, notice: 'Blog created successfully'
    else
      flash.now[:error] = 'Unable to create blog'
      handle_failed_blog_creation
    end
  end

  def edit
    @categories = Category.all.pluck(:name, :id)
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog Updated Successfully' }
      else
        flash.now[:error] = 'Unable to update blog'
        handle_failed_blog_update
      end
    end
  end

  def destroy
    if @blog.destroy
      redirect_to user_blogs_path(current_user), notice: 'Blog Deleted Successfully'
    else
      render @blog, status: :unprocessable_entity
    end
  end

  private

  def set_blog
    @blog = Blog.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to '/404'
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :summary, :tags, :status, :read_time, :published_at,
                                 :category_id, :video_link, :avatar)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def video_embed_link(original_link)
    original_link.sub('watch?v=', 'embed/')
  end

  def add_start_writing_btn(style = 'btn btn-info')
    if user_signed_in?
      render inline: "<%= link_to 'Start Writing', user_blogs_path(current_user), class: '#{style}' %>"
    else
      render inline: "<button class='#{style}' data-bs-toggle='modal'
                              data-bs-target='#exampleModal'>Start Writing</button>"
    end
  end
end

app/views/blogs/_blog.html.erb
<div class="row blog-cart mb-5 flex-md-row-reverse">
  <div class="col-md-8">
    <a href="<%= "#{blog_path(blog.friendly_id)}" %>", class="text-decoration-none" data-turbo-frame="_top" >
      <div class="short-summary h-3rem fs-16px fw-semibold"><%= blog.title %></div>
      <div class="text-muted mb-2 short-summary fs-14px h-38px lh-18px"><%= blog.summary %> ...</div>
    </a>
    <small class="text-muted fs-14px">
      <%= get_blog_status(blog) %> | 
      <%= blog.read_time %> min read | 
      <%= link_to blog.category.name, blog.category, class: "border text-decoration-none rounded-pill px-2 py-1 light-gray text-center", 
      data: { turbo_frame: "blogs-list" } %>
    </small>
    <hr class="text-muted" />
    <div class="pb-2 d-flex mt-3">
      <div class="align-self-center pe-2">
        <%= image_tag(blog.user.user_avatar, class: "rounded-circle blog-circle-img") %>
      </div>
      <div>
        <span class="fw-semibold"><%= blog.user.name %></span><br/>
        <span class="fw-light text-muted fs-14px"><%= blog.user.user_summary&.title || 'Blogger at Education Courier' %></span>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <%= image_tag(blog.blog_avatar, class: "blog-thumbnail rounded-4")%> 
  </div>
</div>

app/views/blogs/_blog_form.html.erb
<div data-controller="blogs", id="blog_form">
  <%= form_with model: @blog, url: blog_form_url(@blog) do |form| %>
    <div class="field mb-3">
      <%= form.label :title, class: 'form-label text-muted' %>
      <em class="text-muted">: A single line title</em><br />
      <%= form.text_area(:title, rows: '2', class: "form-control", required: true) %>
    </div>

    <div class="field mb-3">
      <%= form.label :content, class: 'form-label text-muted' %><br />
      <div data-blogs-target="quillEditor"></div>
      <%= form.hidden_field :content, id: "blog_content", required: true %>
    </div>

    <div class="field mb-3">
      <%= form.label :summary, class: 'form-label text-muted' %>
      <em class="text-muted">: Try to complete with-in three lines</em><br />
      <%= form.text_area(:summary, rows: '3', class: "form-control", required: true) %>
    </div>

    <div class="field">
      <%= form.label :image, class: 'form-lable text-muted' %><br />
      <%= form.file_field :avatar, class: 'form-control mb-3', accept:'image/*' %>
    </div>

    <div class="field mb-3">
      <%= form.label :video_link, class: 'form-label text-muted' %>
      <em class="text-muted">: Youtube video link (optional)</em><br />
      <%= form.text_field :video_link, placeholder: 'Any video link for blog', class: "form-control" %>
    </div>
    
    <div class="field mb-3">
      <%= form.label :tags, class: 'form-label text-muted' %>
      <em class="text-muted">: Comma seperated </em><br />
      <%= form.text_field :tags, placeholder: 'Ruby, Rails', class: "form-control", required: true  %>
    </div>

    <div class="row">
      <div class="col field mb-3">
        <%= form.label :read_time, class: 'form-label text-muted' %><br />
        <%= form.number_field :read_time, placeholder: '8 Min Read', step: 0.5, class: "form-control", min: 0.5, required: true   %>
      </div>

      <div class="col field mb-3">
        <%= form.label :category_id, class: 'form-label text-muted' %><br />
        <%= form.select :category_id, @categories, {}, class: "form-select" %>
      </div>
    </div>

    <div class="field mb-3">
      <%= form.label :published_at, class: 'form-label text-muted' %>
      <em class="text-muted">: Leave empty to set as draft (optional) </em><br />
      <%= form.datetime_local_field :published_at, include_blank: true, class: "form-control" %>
    </div>

    <div class="actions my-2 text-center">
      <%= link_to "Cancel", :back, class: "btn btn-outline-dark" %>
      <%= form.submit class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/blogs/_blog_react_btns.html.erb
<div class="d-flex border-bottom border-top p-2 mt-3 text-muted justify-content-between" id="blog_react_btns">
  <div class="d-flex">
    <%= add_like_btn(blog.id, 'Blog').html_safe %>
    <span class="align-self-center fw-bold">.</span>
    <span class="align-self-center px-2"><%= display_count(blog.likes.count, 'like') %></span>
  </div>
  <div class="d-flex">
    <a href="#new_comment_form", class="text-muted display-6 px-2"><i class="bi bi-chat-right-dots"></i></a>
    <span class="align-self-center fw-bold">.</span>
    <span class="align-self-center px-2"><%= display_count(blog.comments.count, 'comment') %></span>
  </div>
</div>

app/views/blogs/_featured_blog.html.erb
<div class="col-md">
  <div class="pb-2 d-flex mt-3">
    <div class="align-self-center pe-2">
      <%= image_tag(blog.user.user_avatar, class: "rounded-circle blog-circle-img") %>
    </div>
    <div>
      <span class="fw-semibold"><%= blog.user.name %></span><br/>
      <span class="fw-light text-muted fs-14px"><%= blog.user.user_summary&.title || 'Blogger at Education Courier' %></span>
    </div>
  </div>
  <div class="fw-semibold fs-16px mb-1"><%= link_to blog.title, blog, class: "text-decoration-none short-summary h-3rem" %></div>
  <small class="text-muted">
    <%= date_format(blog.published_at) if blog.published_at.present? %> | 
    <%= blog.read_time %> min read | 
    <%= link_to blog.category.name, blog.category, class: "border text-decoration-none rounded-pill px-2 py-1 light-gray text-center", 
    data: { turbo_frame: "blogs-list" } %>
  </small>
</div>

app/views/blogs/edit.html.erb
<div class="py-5 py-20">
  <h2 class="fw-bolder">Edit Blog</h2>
  <%= render 'blogs/blog_form', blog: @blog %>
</div>

app/views/blogs/index.html.erb
<div class="home-div" >
  <%= link_to '<i class="bi bi-arrow-return-left"></i> Back'.html_safe, :back, class: "btn btn-info" %>
  <div class="row py-4">
    <div class="col">
      <% if current_user.blogs.present? %>
        <h3> Your blogs <span class="text-muted fw-light">( Total: <%= @blogs.count %> )</span></h3>
      <% else %>
        <h4> Continue writing some amazing content</h4>
      <% end %>
    </div>
    <div class="col align-self-center text-end"><%= link_to "Crete New blog", new_user_blog_path, class: "btn btn-success text-white" %></div>
  </div>

  <% if current_user.blogs.exists? %>
    <div class="row mb-3">
      <%= link_to 'All blogs', user_blogs_path(current_user), class: "btn btn-outline-success m-2 col" %>
      <%= link_to 'Only Scheduled blogs', user_blogs_path(current_user, :query =>'scheduled_blogs'), class: "btn btn-outline-success m-2 col" %>
      <%= link_to 'Only Draft blogs', user_blogs_path(current_user, :query =>'draft_blogs'), class: "btn btn-outline-success m-2 col" %>
    </div>
  <% end %>

  
  <div id="blogs_list">
    <% @blogs.each do |blog| %>
      <%= render 'blogs/blog', blog: blog %>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="py-5 py-20">
  <h2 class="fw-bolder">Create New Blog</h2>
  <%= render 'blogs/blog_form', blog: @blog %>
</div>

app/views/blogs/show.html.erb
<div data-controller="share" data-share-title-value="<%= @blog.title%>"
  class="share-btn-container bg-white d-flex flex-sm-column p-sm-2 position-fixed m-sm-3">
  <div class="p-2">
    <a data-share-target="linkedIn" href='#' target="_blank"> <i class="bi bi-linkedin text-primary"></i> </a>
  </div>
  <div class="p-2">
    <a data-share-target="twitter" href='#' target="_blank"> <i class="bi bi-twitter text-info"></i></a>
  </div>
  <div class="p-2">
    <a data-share-target="facebook" href='#' target="_blank"> <i class="bi bi-facebook text-primary"></i> </a>
  </div>
  <div class="p-2">
    <a data-share-target="whatsapp" href='#' target="_blank"> <i class="bi bi-whatsapp text-success"></i> </a>
  </div>
  <div class="p-2">
    <a data-share-target="pinterest" href='#' target="_blank"> <i class="bi bi-pinterest text-danger"></i> </a>
  </div>
</div>
<div class="py-5 py-20">
  <%= link_to '<i class="bi bi-arrow-return-left"></i> Back'.html_safe, :back, class: "btn btn-info mb-3" %>
  <% if can? :edit, @blog %>
    <div class="text-end">
      <%= link_to '<i class="bi bi-pencil-square"></i> Edit blog'.html_safe, edit_blog_path(@blog), class: "btn btn-primary text-white m-2" %>
      <%= link_to '<i class="bi bi-trash"></i> Delete blog'.html_safe, @blog,
          data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger text-white m-2" %>
    </div>
  <% end %>
  <div class="mb-3">
    <h2 class="fw-bolder"><%= @blog.title %></h2>
    <p class="text-muted"><%= @blog.summary %></p>
    <div class="d-flex justify-content-between">
      <div class="d-flex">
        <div class="align-self-center">
          <%= image_tag(@blog.user.user_avatar, class: "rounded-circle blog-circle-img") %> 
        </div>
        <div class="ps-2">
          <span class="fw-semibold"><%= @blog.user.name %></span>
          <span class="text-muted fw-light">| <%= @blog.user.user_summary&.title || 'Blogger at Education Courier' %></span><br/>
          <small class="text-muted">
            <%= get_blog_status(@blog) %> | 
            <%= @blog.read_time %> min read | 
            <%= link_to @blog.category.name, @blog.category, 
            class: "border text-decoration-none rounded-pill px-2 py-1 light-gray text-center" %>
          </small>
        </div>
      </div>
    </div>
    <%= render 'blog_react_btns', blog: @blog %>
    <div class="mt-3">
      <%= image_tag(@blog.blog_avatar, class: "max-size-fill-available") %> 
    </div>
    <% if @blog.video_link.present? %>
      <div class="my-3">
        <iframe src='<%= video_embed_link(@blog.video_link) %>' title="YouTube video player" 
        frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; 
        picture-in-picture; web-share" allowfullscreen class="youtube-iframe"></iframe>
      </div>
    <% end %>
    <p class="mt-3"><%= @blog.content.html_safe %></p>
    <div class="d-flex flex-wrap">
      <% @blog.tags.split(',').each do |tag| %>
        <%= link_to tag, category_path(@blog.category_id, tag: tag), class: "text-center border rounded-pill p-2 m-2 light-gray text-decoration-none" %>
      <% end %>
    </div>
  </div>

  <%= display_comments_count(@blog.comments.count) %>
  <%= render 'comments/form', comment: Comment.new, parent: nil %>

  <div id="comments">
    <%= render @blog.parent_comments, blog: @blog %>
  </div>
</div>