config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i[create show], shallow: true do
    resources :blogs do
      resources :comments, except: %i[show]
    end
  end

  resources :categories
  resources :likes, only: %i[create destroy]

  get '/about', to: 'pages#about', as: 'about_page'
  get '/contact', to: 'pages#contact', as: 'contact_page'
  get '/faqs', to: 'pages#faqs', as: 'faqs_page'

  post '/subscribe', to: 'users#subscribe', as: 'subscribe'

  post '/feedback', to: 'comments#guest_user_feedback', as: 'guest_user_feedback'

  match '*path', via: :all, to: redirect('/404'), constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :blog
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :children, class_name: 'Comment', foreign_key: :parent_id, inverse_of: 'parent', dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  scope :created_today, -> { where('Date(created_at) = ?', Time.zone.today) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsConcern
  load_and_authorize_resource
  skip_before_action :authenticate_user!, only: %i[index new guest_user_feedback]
  before_action :set_comment, only: %i[edit update destroy]
  before_action :set_blog, only: %i[index new create]
  before_action :set_parent, only: %i[index new create]

  def index
    @comments = if params[:parent_id].present?
                  Comment.find(params[:parent_id]).children
                else
                  @blog.comments
                end
  end

  def new
    @comment = Comment.new
  end

  def create
    params[:parent_id].present? ? create_child_comment : create_comment
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      flash.now[:notice] = 'Comment Updated Successfully'
      handle_successful_comment_update
    else
      flash.now[:error] = 'Unable to update Comment'
      handle_failed_comment_update
    end
  end

  def destroy
    @comment.destroy
    flash.now[:notice] = 'Comment deleted successfully'
    handle_successful_comment_destroy
  rescue StandardError
    flash.now[:error] = 'Unable to delete comment'
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.prepend('body_tag', partial: 'shared/toast') }
    end
  end

  def guest_user_feedback
    if validate_feedback_params
      UserMailer.guest_user_feedback(params[:name], params[:email], params[:feedback]).deliver_later
      handle_successful_guest_feedback
    else
      handle_failed_guest_feedback
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_parent
    @parent = Comment.find(params[:parent_id]) if params[:parent_id].present?
  end

  def set_blog
    @blog = Blog.friendly.find(params[:blog_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def validate_feedback_params
    params[:name].present? && params[:email].present? && params[:feedback].present?
  end
end

app/controllers/concerns/comments_helper.rb
module CommentsHelper
  extend ActiveSupport::Concern
  include CommentsCreationHelpers
  def handle_successful_comment_update
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("comment_#{@comment.id}_content", partial: 'comment_content',
                                                                 locals: { comment: @comment, blog: @comment.blog }),
          turbo_stream.prepend('body_tag', partial: 'shared/toast')
        ]
      end
    end
  end

  def handle_failed_comment_update
    format.turbo_stream do
      render turbo_stream: [
        turbo_stream.remove('error_messages'),
        turbo_stream.prepend("comment_#{@comment.id}_content", partial: 'shared/error_messages',
                                                               locals: { object: @comment }),
        turbo_stream.prepend('body_tag', partial: 'shared/toast')
      ]
    end
  end

  def handle_successful_comment_destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(helpers.dom_id(@comment).to_s),
          turbo_stream.replace('comments_count', inline: '<%= display_comments_count(@comment.blog.comments.count) %>'),
          turbo_stream.prepend('body_tag', partial: 'shared/toast')
        ]
      end
    end
  end

  def generate_mails
    UserMailer.notify_user_about_comment(@comment).deliver_later
    UserMailer.notify_user_about_reply(@comment).deliver_later
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_parent
    @parent = Comment.find(params[:parent_id]) if params[:parent_id].present?
  end

  def set_blog
    @blog = Blog.find(params[:blog_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_comment.html.erb
<div id='<%= "comment_#{comment.id}" %>'>
  <div class="d-flex align-items-center mt-2">
    <%= image_tag(comment.user.user_avatar, class: "rounded-circle blog-circle-img") %>  
    <span class="fw-semibold ms-2"><%= comment.user.name %></span>
    <% if comment.user == comment.blog.user %><span class="text-danger ps-2">Author</span><% end %>
    <span class="text-muted"><i class="bi bi-dot fs-2"></i></span>
    <%= date_format(comment.created_at) %>
  </div>

  <%= render "comments/comment_content", comment: comment, blog: blog %>
</div>

app/views/comments/_comment_content.html.erb
<%= turbo_frame_tag "#{dom_id(comment)}_content" do %>
  <div class="border rounded p-3 ms-4">
    <div class="p-2 rounded-1 mb-2 text-bg-light-gray"><%= comment.content %></div>
    <div class="d-flex justify-content-between">
      <div class="d-flex text-muted">
        <%= add_like_btn(comment.id, 'Comment').html_safe %>.
        <span class="px-2 align-self-center"><%= display_count(comment.likes.count, 'like') %></span> |
        <%= add_reply_btn(comment).html_safe %>
      </div>

      <% if can? :edit, comment %>
        <div>
          <%= link_to 'Edit', edit_comment_path(comment), class: "text-decoration-none text-primary me-2" %>
          <%= link_to 'Delete', comment, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-decoration-none text-danger" %>
        </div>
      <% end %>
    </div>

    <% if comment.children.present? %>
      <%= render 'comments/replies', comment: comment, blog: blog %>
    <% end %>
    
    <%= turbo_frame_tag "#{dom_id(comment)}_child_comment" do %>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <%= turbo_frame_tag comment_form_id(parent) do %>
    <div class="border border-dark p-5 rounded mt-2">
      <% unless parent.present? %> <h5>Any thing that can be improved?</h5> <% end %>
      <%= form_with url: blog_comments_path(@blog, parent_id: parent), method: :post, model: comment do |form| %>
        <div class="field">
          <%= form.text_area(:content, rows: '3', class: "form-control mb-3", required: true, placeholder: "Your feedback") %>
        </div>
        <div class="field">
          <%= form.submit class: "btn btn-dark" %>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <div class="border border-dark p-5 rounded mt-2" id="new_comment_form">
    <h5>Any thing that can be improved?</h5>
    <form data-bs-toggle='modal' data-bs-target='#exampleModal'>
      <div class="field">
        <textarea rows='3' placeholder="Your feedback", class="form-control mb-3"></textarea>
        </div>
      <div class="field">
        <input type="submit" value="Submit" class="btn btn-dark" disabled="true">
      </div>
    </form>
  </div>
<% end %>

app/views/comments/_replies.html.erb
<%= turbo_frame_tag "#{dom_id(comment)}_replies" do %>
  <%= link_to "<i class='bi bi-arrow-return-right'></i> #{display_count(comment.children.count, 'reply')}".html_safe, blog_comments_path(blog, parent_id: comment.id), class: "fw-semibold btn-link text-muted text-decoration-none" %>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag "#{dom_id(@comment)}_content" do %>
  <div class="border border-1 rounded p-3 ms-4">
    <%= form_with model: @comment do |form| %>
      <div class="field">
        <%= form.text_area(:content, rows: '3', class: "form-control mb-3", required: true, placeholder: "Your feedback (Optional)") %>
      </div>
      <div class="field">
        <%= form.submit class: "btn btn-dark" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/comments/index.html.erb
<%= turbo_frame_tag "#{dom_id(@parent)}_replies" do %>
  <%= render @comments, blog: @blog %>
<% end %>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment, parent: @parent %>