config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i[create show], shallow: true do
    resources :blogs do
      resources :comments, except: %i[show]
    end
  end

  resources :categories
  resources :likes, only: %i[create destroy]

  get '/about', to: 'pages#about', as: 'about_page'
  get '/contact', to: 'pages#contact', as: 'contact_page'
  get '/faqs', to: 'pages#faqs', as: 'faqs_page'

  post '/subscribe', to: 'users#subscribe', as: 'subscribe'

  post '/feedback', to: 'comments#guest_user_feedback', as: 'guest_user_feedback'

  match '*path', via: :all, to: redirect('/404'), constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/views/shared/_error_messages.html.erb
<div id="error_messages">
  <% if object.errors.any? %>
    <div style="color: red">
      <ul>
        <% object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="text-center text-lg-start border-top">
  <div class="container p-4">
    <div class="row">
      <div class="col-md-2">
        <%= image_tag 'favicon.png', class: 'max-size-fill-available' %>
      </div>
      <div class="col-md-2">
        <div class="fw-semibold mb-3">PAGES</div>
        <ul class="nav flex-column">
          <li class="nav-item mb-2 hover-pad"><%= link_to '<i class="bi bi-book"></i> BLOGS'.html_safe, root_path, class: "text-decoration-none fw-normal fs-14px text-dark" %></li>
          <li class="nav-item mb-2 hover-pad"><%= link_to '<i class="bi bi-tags"></i> CATEGORIES'.html_safe, categories_path, class: "text-decoration-none fw-normal fs-14px text-dark" %></li>
        </ul>
      </div>
      <div class="col-md-3">
        <div class="fw-semibold mb-3">ABOUT US</div>
        <ul class="nav flex-column">
          <li class="nav-item mb-2 hover-pad"><%= link_to '<i class="bi bi-info-circle"></i> ABOUT US'.html_safe, about_page_path, class: "text-decoration-none fw-normal fs-14px text-dark" %></li>
          <li class="nav-item mb-2 hover-pad"><%= link_to '<i class="bi bi-envelope-fill"></i> CONTACT US'.html_safe, contact_page_path, class: "text-decoration-none fw-normal fs-14px text-dark" %></li>
          <li class="nav-item mb-2 hover-pad"><%= link_to "<i class='bi bi-question-circle'></i> FAQ's".html_safe, faqs_page_path, class: "text-decoration-none fw-normal fs-14px text-dark" %></li>
        </ul>
      </div>
      <div class="col-md-5">
        <div class="fw-semibold mb-3">Subscribe to our monthly newsletter</div>
        <div class="fs-14px mb-4 fw-light">Receive a monthly email packed with the newest news, articles, and useful resources. Stay up to date effortlessly!</div>
          <%= form_with url: subscribe_path, class: 'row g-3' do |form| %>
            <div class="col-lg-8">
              <%= form.text_field :email, placeholder: 'Enter your email', autocomplete: 'off', required: true, class: 'form-control'%>
            </div>
            <div class="col-lg-4">
              <%= form.submit "Subscribe", class: 'btn btn-primary' %>
            </div>
          <% end %>
      </div>
    </div>
  </div>

  <div class="container d-flex justify-content-between pt-3 border-top">
    <p class="fw-light fs-14px">&copy; 2023 Education Courier. All rights reserved.</p>
    <ul class="list-unstyled d-flex mb-2">
      <li class="ms-3"><a class="link-dark" href="https://github.com/usman-zulfiqar065" target = "_blank"><i class="bi bi-github fs-3 text-secondary"></i></a></li>
      <li class="ms-3"><a class="link-dark" href="https://www.linkedin.com/in/usman-zulfiqar/" target = "_blank"><i class="bi bi-linkedin fs-3 text-secondary"></i></a></li>
    </ul>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light border-bottom px-lg-5 sticky-top">
  <div class="container-fluid mx-lg-5">
    <%= image_tag("favicon.png", class: "navbar-brand py-0") %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-auto">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "text-decoration-none px-lg-4 fw-semibold fs-14px" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Categories', categories_path, class: "text-decoration-none px-lg-4 fw-semibold fs-14px" %>
        </li>
        <li class="nav-item dropdown">
          <a class="text-decoration-none dropdown-toggle fs-14px px-lg-4 fw-semibold" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Company
          </a>
          <div class="dropdown-menu rounded-4 shadow-sm p-2 width-25rem" aria-labelledby="navbarDropdownMenuLink">
            <a href="/about" class="dropdown-item rounded-2 mb-2">
              <div class="fw-semibold fs-14px">About Us</div>
              <div class="fs-14px fw-light ws-normal text-muted">Discover the story behind our mission, explore what we have to offer, 
                and learn more about who we are</div>
            </a>
            <a href="/contact" class="dropdown-item rounded-2 mb-2">
              <div class="fw-semibold fs-14px">Contact Us</div>
              <div class="fs-14px fw-light ws-normal text-muted">Want to share your thoughts, suggestions, or any issues you've encountered while using the website</div>
            </a>
            <a href="/faqs" class="dropdown-item rounded-2 mb-2">
              <div class="fw-semibold fs-14px">FAQ's</div>
              <div class="fs-14px fw-light ws-normal text-muted">Have any question? Please have a look at some frequently asked questions</div>
            </a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item align-self-lg-center">
          <%= add_start_writing_btn('btn btn-primary text-white') %>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(set_navbar_user_url, class: "rounded-circle nav-avatar") %>
          </a>
          <div class="dropdown-menu rounded-4 shadow-sm p-2" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <% if current_user.blogger? || current_user.admin? %>
                <%= link_to '<i class="bi bi-person-check-fill"></i> Admin Pannel'.html_safe, admin_root_path, class: "dropdown-item rounded-2 mb-2"%>
              <% end %>
              <%= link_to '<i class="bi bi-book"></i> My Blogs'.html_safe, user_blogs_path(current_user), class: "dropdown-item rounded-2 mb-2"%>
              <%= link_to '<i class="bi bi-person-bounding-box"></i> My Profile'.html_safe, current_user, class: "dropdown-item rounded-2 mb-2" %>
            <% else %>
              <%= link_to '<i class="bi bi-box-arrow-in-right"></i> Sign in'.html_safe, new_user_session_path, class: "dropdown-item rounded-2 mb-2" %>
              <%= link_to '<i class="bi bi-person-plus"></i> Sign up'.html_safe, new_user_registration_path, class: "dropdown-item rounded-2 mb-2" %>
            <% end %>
            <% if user_signed_in? %>
              <hr class="dropdown-divider">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn' %>
            <% end %>
          </div>
        </li>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_signin_btns_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="fw-bolder">Welcome to <span class="fontfamily-none">EDUCATION COURIER</span></h4>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body p-4">
      <div class='text-center mb-2 fw-semibold'>Become a part of our community</div>
      <div>
        Please
        <%= link_to "Sign up", new_user_registration_path, class: 'text-gold text-decoration-none'%>
        OR
        <%= link_to "Sign in to your existing account", new_user_session_path, class: 'text-gold text-decoration-none'%>
        to continue
      </div>
    </div>
    <div class="container">
      <div class="row text-secondary">
        <div class="col-md-5 p-0"><hr></div>
        <span class="col-md p-0 text-center align-self-center"> or</span>
        <div class="col-md-5 p-0 "> <hr></div>
      </div>
    </div>

    <%- User.omniauth_providers.each do |provider| %>
      <div class="m-3 mt-0">
        <%= button_to "#{image_tag('google_icon.svg')} Continue with Google".html_safe, omniauth_authorize_path(User, provider), data: { turbo: false },
            class: 'bg-white border rounded-2  text-center w-100 p-2 pointer-event google-login' %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_toast.html.erb
<% if flash.present? %>
  <div class ="flash" >
    <% flash.each do |flash_type, message| %>
      <div class="flash__message <%= flash_type %>" 
        data-controller="flash"
        data-action="animationend->flash#remove"
      >
        <%= message %>
      </div>
    <% end %>
  </div>
<% end %>